### ISSUE TITLE
Gemfile

### ISSUE THREAD

**Issue by tonkonogov** [ossert/ossert#6]
Hi @sclinede, I wonder why do you build this project as a gem? 
In my opinion, gem is suitable for utility libraries or any CLI tools (like rake, sass etc.), but in this case I don't see it as a dependency for something nor like a tool to use on all machines. I see it more like a web-based project, which marks open source projects. Obviously, it doesn't make sense to assess projects by everyone (cli-gem-style way).

**Comment by sclinede** [comment]
It was started as experiment, and I needed to structure all code somehow. This is "core" gem for "ossert-web" and later we'll have a CLI which maybe partially will depend on it too. 
I've separeted here data processing and their storage. Some classes (i.e. presenters) will move to ossert-web. So. Yeah it's a bit mess now, but it works)
If you could help with better structure create a PR. I really appreciate it!

**Comment by tonkonogov** [comment]
Ok, it makes more sense now. Splitting codebase into several gems is a good way to make it more isolated, although I didn't face it much in my practice. Let's see what we will get later.
